;; -*- mode: eask; lexical-binding: t -*-

(package "definition-lookup-mode"
         "0.1.0"
         "A mode for looking up definitions")

(website-url "https://github.com/jgrey4296/definition-lookup-mode")
(keywords )

(package-file "definition-lookup-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "30.2")
(depends-on "dash")
